server:
  port: 8090
  error:
    include-stacktrace: always
spring:
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth.dev.briolink.com/auth/realms/briolink/protocol/openid-connect/certs
app:
  app-endpoints:
    locationservice:
dgs:
  graphql:
    introspection:
      enabled: true
location-service:
  api:
    url: http://192.168.0.23:8070/
    version: 1
