#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  profiles:
    active: ${env.spring_profiles_active:local}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/${env.spring_profiles_active}_companyservice
    username: ${env.DB_USER:ok}
    password: ${env.DB_PASSWORD:ok}
    hikari:
      idle-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        metadata_builder_contributor: com.briolink.servicecompanyservice.common.jpa.Functions
    generate-ddl: false
    show-sql: false
  liquibase:
    defaultSchema: write
    change-log: migration/master.yml
cloud:
  aws:
    stack:
      auto: false
dgs:
  graphql:
    path: /
app:
  aws:
    s3:
      name: ${env.S3_BUCKET_NAME:briolink}
event:
  publisher:
    sns-name: bl-network-${env.spring_profiles_active}.fifo
