server:
  port: 8085
spring:
  profiles:
    active: ${env.spring_profiles_active:local}
  datasource:
    url: jdbc:postgresql://${env.DB_HOST:localhost}:${env.DB_PORT:5432}/${env.spring_profiles_active}_companyservice
    username: ${env.DB_USER:root}
    password: ${env.DB_PASSWORD:root}
    hikari:
      idle-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        metadata_builder_contributor: com.briolink.servicecompanyservice.common.jpa.Functions
        jdbc:
          batch_size: 60
    generate-ddl: false
    show-sql: false
cloud:
  aws:
    stack:
      auto: false
event:
  listener:
    sqs-name: bl-network-${env.spring_profiles_active}-companyservice-service.fifo
app:
  app-endpoints:
    locationservice: http://location-service.${env.spring_profiles_active}.svc.cluster.local/
