logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8095
spring:
  jpa:
    show-sql: true
app:
  app-endpoints:
    locationservice: http://192.168.0.23:8070/
