server:
  port: 8085
spring:
  profiles:
    active: ${env.spring_profiles_active:local}
  datasource:
    url: jdbc:mariadb://${env.DB_HOST:localhost}:${env.DB_PORT:3306}/
    username: ${env.DB_USER:root}
    password: ${env.DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        jdbc:
          batch_size: 60
    generate-ddl: false
    show-sql: false
cloud:
  aws:
    stack:
      auto: false
app:
  db:
    schema-prefix: ${env.spring_profiles_active}_company_service
event:
  listener:
    enabled: true
    sqs-name: bl-network-${env.spring_profiles_active}-service-company-service.fifo
