apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.werf.name }}.{{ .Values.werf.env }}.briolink.com"
    cert-manager.io/cluster-issuer: cert-manager
  name: {{ .Values.werf.name }}
spec:
  rules:
    - host: "{{ .Values.werf.name }}.{{ .Values.werf.env }}.briolink.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.werf.name }}
                port:
                  number: 8080
  tls:
    - hosts:
        - "{{ .Values.werf.name }}.{{ .Values.werf.env }}.briolink.com"
      secretName: "{{ .Values.werf.name }}-{{ .Values.werf.env }}-tls"
